// ============================================
// RESTAURANT (DINE-IN) MENU CATALOG
// ============================================

export const DEFAULT_RESTAURANT_ITEMS = [
  // Starters
  {
    id: 'paneer-tikka',
    name: 'Paneer Tikka',
    category: 'starters',
    description: 'Chargrilled cubes of Indian cottage cheese marinated in tandoori spices with bell peppers and onions. Smoky, succulent, and served with mint chutney.',
    price: 220,
    unit: 'per plate',
    image: '/images/restaurant/paneer-tikka.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'veg-pakora',
    name: 'Veg Pakora',
    category: 'starters',
    description: 'Crispy golden fritters made from a medley of fresh vegetables coated in spiced chickpea flour batter. Deep-fried and served with tangy coriander mint chutney.',
    price: 120,
    unit: 'per plate',
    image: '/images/restaurant/veg-pakora.png',
    isVeg: true,
    isAvailable: true,
  },
  // Sabzis
  {
    id: 'dal-makhani',
    name: 'Dal Makhani',
    category: 'sabzi',
    description: 'Creamy, buttery black lentils and kidney beans slow-cooked overnight with tomatoes, cream, and aromatic spices. A rich, comforting North Indian staple.',
    price: 180,
    unit: 'per bowl',
    image: '/images/restaurant/dal-makhani.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'paneer-butter-masala',
    name: 'Paneer Butter Masala',
    category: 'sabzi',
    description: 'Soft paneer cubes swimming in a luscious, creamy tomato-cashew gravy kissed with butter and kasuri methi. The undisputed king of North Indian vegetarian curries.',
    price: 220,
    unit: 'per bowl',
    image: '/images/restaurant/paneer-butter-masala.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'aloo-gobi',
    name: 'Aloo Gobi',
    category: 'sabzi',
    description: 'Home-style cauliflower and potato curry cooked with turmeric, cumin, and fresh spices. A simple, wholesome dish that tastes like comfort and warmth.',
    price: 140,
    unit: 'per bowl',
    image: '/images/restaurant/aloo-gobi.png',
    isVeg: true,
    isAvailable: true,
  },
  // Roti Options
  {
    id: 'plain-roti',
    name: 'Plain Roti',
    category: 'roti',
    description: 'Soft, hand-rolled whole wheat flatbread cooked on a traditional tawa. Light, fluffy, and the perfect partner for any curry or dal.',
    price: 20,
    unit: 'per piece',
    image: '/images/restaurant/roti-naan.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'butter-naan',
    name: 'Butter Naan',
    category: 'roti',
    description: 'Pillowy soft, tandoor-baked naan bread brushed generously with melted butter. Golden, slightly charred, with a delightful smoky flavor.',
    price: 50,
    unit: 'per piece',
    image: '/images/restaurant/roti-naan.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'tandoori-roti',
    name: 'Tandoori Roti',
    category: 'roti',
    description: 'Wholesome whole wheat roti cooked in a blazing tandoor oven. Slightly crisp on the outside, soft within, with beautiful char marks and smoky aroma.',
    price: 30,
    unit: 'per piece',
    image: '/images/restaurant/roti-naan.png',
    isVeg: true,
    isAvailable: true,
  },
  // Thali Options
  {
    id: 'regular-thali',
    name: 'Regular Thali',
    category: 'thali',
    description: 'A complete vegetarian meal: 2 sabzis, dal, rice, 3 rotis, raita, salad, and a sweet. A wholesome, balanced, and satisfying Indian dining experience.',
    price: 250,
    unit: 'per thali',
    image: '/images/restaurant/thali.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'deluxe-thali',
    name: 'Deluxe Thali',
    category: 'thali',
    description: 'Upgraded thali with 3 premium sabzis, dal makhani, jeera rice, 4 assorted rotis/naan, raita, papad, pickle, salad, and 2 desserts for a royal feast.',
    price: 350,
    unit: 'per thali',
    image: '/images/restaurant/thali.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'special-thali',
    name: 'Special Thali',
    category: 'thali',
    description: 'Our grandest thali: 4 special sabzis, dal makhani, biryani rice, unlimited rotis, paneer tikka starter, 3 desserts, buttermilk, and papad. A true royal banquet.',
    price: 450,
    unit: 'per thali',
    image: '/images/restaurant/thali.png',
    isVeg: true,
    isAvailable: true,
  },
];

export const RESTAURANT_CATEGORIES = [
  { id: 'all', name: 'All Items' },
  { id: 'starters', name: 'Starters' },
  { id: 'sabzi', name: 'Sabzis' },
  { id: 'roti', name: 'Roti Options' },
  { id: 'thali', name: 'Thali Options' },
];
