// ============================================
// RESTAURANT (DINE-IN) MENU CATALOG
// ============================================

export const DEFAULT_RESTAURANT_ITEMS = [
  // Starters
  {
    id: 'paneer-tikka',
    name: 'Paneer Tikka',
    category: 'starters',
    description: 'Thick-cut paneer cubes marinated overnight in a smoky tandoori spice paste with bell peppers and onions, then chargrilled until the edges caramelize. Served sizzling with fresh mint chutney and lemon wedge.',
    price: 220,
    unit: 'per plate',
    image: '/images/restaurant/paneer-tikka.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'veg-pakora',
    name: 'Veg Pakora',
    category: 'starters',
    description: 'A crispy platter of mixed vegetable fritters — onion rings, potato slices, spinach leaves, and green chillies — all dipped in spiced besan batter and fried until golden. Served hot with our tangy coriander-mint dip.',
    price: 120,
    unit: 'per plate',
    image: '/images/restaurant/veg-pakora.png',
    isVeg: true,
    isAvailable: true,
  },
  // Sabzis
  {
    id: 'dal-makhani',
    name: 'Dal Makhani',
    category: 'sabzi',
    description: 'Whole black urad dal and rajma slow-simmered for hours with tomatoes, ginger, and a generous swirl of fresh cream and butter. The kind of rich, velvety dal you dream about. A Shree Shyam signature that keeps regulars coming back.',
    price: 180,
    unit: 'per bowl',
    image: '/images/restaurant/dal-makhani.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'paneer-butter-masala',
    name: 'Paneer Butter Masala',
    category: 'sabzi',
    description: 'Soft, fresh paneer cubes in a silky tomato-cashew gravy finished with a knob of butter and a sprinkle of kasuri methi. Creamy, mildly sweet, and universally loved — the dish that defines North Indian comfort food.',
    price: 220,
    unit: 'per bowl',
    image: '/images/restaurant/paneer-butter-masala.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'aloo-gobi',
    name: 'Aloo Gobi',
    category: 'sabzi',
    description: 'Tender cauliflower florets and golden potato chunks tossed in a home-style masala of turmeric, cumin, and fresh coriander. Simple, satisfying, and cooked exactly the way your kitchen at home would — only better.',
    price: 140,
    unit: 'per bowl',
    image: '/images/restaurant/aloo-gobi.png',
    isVeg: true,
    isAvailable: true,
  },
  // Roti Options
  {
    id: 'plain-roti',
    name: 'Plain Roti',
    category: 'roti',
    description: 'Hand-rolled whole wheat roti puffed fresh on a hot tawa. Soft, light, and perfectly round — the ideal companion for any sabzi or dal on the menu.',
    price: 20,
    unit: 'per piece',
    image: '/images/restaurant/roti-naan.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'butter-naan',
    name: 'Butter Naan',
    category: 'roti',
    description: 'Pillowy soft naan baked against the walls of our clay tandoor until it puffs up with beautiful charred spots. Brushed with a generous layer of melted butter the moment it comes out. Tears perfectly.',
    price: 50,
    unit: 'per piece',
    image: '/images/restaurant/roti-naan.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'tandoori-roti',
    name: 'Tandoori Roti',
    category: 'roti',
    description: 'Wholesome atta roti pressed thin and slapped into a roaring tandoor. The outside gets a slight crackle and smoky char while the inside stays wonderfully soft. Healthier than naan, just as satisfying.',
    price: 30,
    unit: 'per piece',
    image: '/images/restaurant/roti-naan.png',
    isVeg: true,
    isAvailable: true,
  },
  // Thali Options
  {
    id: 'regular-thali',
    name: 'Regular Thali',
    category: 'thali',
    description: 'A satisfying everyday meal on a single plate: 2 seasonal sabzis, tadka dal, steamed rice, 3 fresh rotis, cool raita, crunchy salad, and a sweet to finish. Everything you need, nothing you don\'t.',
    price: 250,
    unit: 'per thali',
    image: '/images/restaurant/thali.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'deluxe-thali',
    name: 'Deluxe Thali',
    category: 'thali',
    description: 'For those who want more: 3 premium sabzis including paneer, rich dal makhani, fragrant jeera rice, 4 assorted rotis and naan, raita, crispy papad, tangy pickle, fresh salad, and 2 desserts. A feast that fills the soul.',
    price: 350,
    unit: 'per thali',
    image: '/images/restaurant/thali.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'special-thali',
    name: 'Special Thali',
    category: 'thali',
    description: 'Our grandest offering: 4 chef\'s special sabzis, dal makhani, aromatic biryani rice, unlimited rotis, paneer tikka starter, 3 handpicked desserts, chilled buttermilk, and papad. The full Shree Shyam royal experience.',
    price: 450,
    unit: 'per thali',
    image: '/images/restaurant/thali.png',
    isVeg: true,
    isAvailable: true,
  },
];

export const RESTAURANT_CATEGORIES = [
  { id: 'all', name: 'All Items' },
  { id: 'starters', name: 'Starters' },
  { id: 'sabzi', name: 'Sabzis' },
  { id: 'roti', name: 'Roti Options' },
  { id: 'thali', name: 'Thali Options' },
];
