// ============================================
// SWEETS & SNACKS CATALOG
// ============================================

export const DEFAULT_SWEETS = [
  {
    id: 'bhujia',
    name: 'Bhujia',
    category: 'snacks',
    description: 'Our signature thin-sev bhujia — crispy chickpea flour noodles tossed in a secret Rajasthani masala blend. Light, crunchy, and absolutely irresistible with evening chai. A Shree Shyam bestseller that keeps Golaghat coming back.',
    price: 80,
    unit: 'per 250g',
    image: '/images/sweets/bhujia.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'cookies',
    name: 'Nankhatai Cookies',
    category: 'snacks',
    description: 'Buttery, crumbly desi shortbread baked fresh daily with pure ghee, roasted besan, and crushed cardamom. Each bite melts on your tongue. Perfect for gifting or enjoying with a cup of masala chai.',
    price: 120,
    unit: 'per 250g',
    image: '/images/sweets/cookies.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'gulab-jamun',
    name: 'Gulab Jamun',
    category: 'sweets',
    description: 'Pillowy soft khoya dumplings, golden-fried and drenched in warm rose-cardamom sugar syrup until they soak up every drop of sweetness. Served warm — the way they taste best. No celebration in Golaghat is complete without these.',
    price: 150,
    unit: 'per 500g',
    image: '/images/sweets/gulab-jamun.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'rasgulla',
    name: 'Rasgulla',
    category: 'sweets',
    description: 'Feather-light, spongy chenna balls simmered gently in a delicate rosewater sugar syrup. Each rasgulla bursts with sweetness the moment you bite in. Fresh, soft, and made from pure milk — the Bengali classic done right.',
    price: 140,
    unit: 'per 500g',
    image: '/images/sweets/rasgulla.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'kaju-barfi',
    name: 'Kaju Barfi',
    category: 'sweets',
    description: 'Velvety smooth cashew fudge cut into perfect diamonds and adorned with edible silver vark. Made with premium whole cashews and pure ghee — no shortcuts. Our most gifted sweet for weddings, Diwali, and special occasions.',
    price: 280,
    unit: 'per 500g',
    image: '/images/sweets/barfi.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'besan-ladoo',
    name: 'Besan Ladoo',
    category: 'sweets',
    description: 'Aromatic golden ladoos made by slow-roasting chickpea flour in desi ghee until it releases that unmistakable nutty fragrance. Sweetened with powdered sugar and studded with crunchy almonds. A homemade taste you can trust.',
    price: 160,
    unit: 'per 500g',
    image: '/images/sweets/ladoo.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'jalebi',
    name: 'Jalebi',
    category: 'sweets',
    description: 'Crispy, juicy spirals fried to a bright saffron orange and dunked in hot sugar syrup right off the kadhai. The outside cracks, the inside oozes sweetness. Best enjoyed piping hot — the way Golaghat loves them.',
    price: 100,
    unit: 'per 500g',
    image: '/images/sweets/jalebi.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'peda',
    name: 'Mathura Peda',
    category: 'sweets',
    description: 'Rich, dense milk fudge discs crafted by slow-reducing fresh khoya with sugar and a whisper of cardamom. Crowned with saffron threads and crushed pistachios. A temple-city recipe we have perfected over years.',
    price: 200,
    unit: 'per 500g',
    image: '/images/sweets/peda.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'motichoor-ladoo',
    name: 'Motichoor Ladoo',
    category: 'sweets',
    description: 'Melt-in-your-mouth ladoos shaped from hundreds of tiny pearl-like boondi drops, each one perfectly spiced with cardamom and saffron. Finished with a touch of silver vark. The quintessential Indian celebration sweet.',
    price: 180,
    unit: 'per 500g',
    image: '/images/sweets/motichoor-ladoo.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'samosa',
    name: 'Samosa',
    category: 'snacks',
    description: 'Shatteringly crispy pastry shells stuffed with a spicy filling of hand-mashed potatoes, green peas, and toasted cumin. Served with our house-made tamarind chutney and fiery green chutney. Golaghat\'s favourite tea-time snack.',
    price: 50,
    unit: 'per 2 pieces',
    image: '/images/sweets/samosa.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'namak-pare',
    name: 'Namak Pare',
    category: 'snacks',
    description: 'Crunchy diamond-shaped crackers made with maida, ajwain seeds, and just the right amount of salt. Fried until perfectly golden and stored fresh. An everyday munching snack that pairs beautifully with chai or pickle.',
    price: 70,
    unit: 'per 250g',
    image: '/images/sweets/namak-pare.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'mathri',
    name: 'Mathri',
    category: 'snacks',
    description: 'Flaky, layered Rajasthani crackers with a satisfying crunch in every bite. Seasoned with ajwain and coarse black pepper, then deep-fried to golden perfection. The kind of snack that disappears before you know it.',
    price: 90,
    unit: 'per 250g',
    image: '/images/sweets/mathri.png',
    isVeg: true,
    isAvailable: true,
  },
];

export const SWEET_CATEGORIES = [
  { id: 'all', name: 'All Items' },
  { id: 'sweets', name: 'Sweets' },
  { id: 'snacks', name: 'Snacks' },
];
