// ============================================
// SWEETS & SNACKS CATALOG
// ============================================

export const DEFAULT_SWEETS = [
  {
    id: 'bhujia',
    name: 'Bhujia',
    category: 'snacks',
    description: 'Crispy, thin chickpea flour noodles seasoned with a blend of Rajasthani spices. A crunchy, addictive namkeen snack perfect with chai or as a party appetizer.',
    price: 80,
    unit: 'per 250g',
    image: '/images/sweets/bhujia.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'cookies',
    name: 'Nankhatai Cookies',
    category: 'snacks',
    description: 'Traditional Indian shortbread cookies made with ghee, besan, and cardamom. Golden, crumbly, and melt-in-the-mouth — a tea-time classic everyone loves.',
    price: 120,
    unit: 'per 250g',
    image: '/images/sweets/cookies.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'gulab-jamun',
    name: 'Gulab Jamun',
    category: 'sweets',
    description: 'Soft, golden-brown milk solid dumplings deep-fried and soaked in fragrant rose-cardamom sugar syrup. An iconic Indian dessert with a melt-in-mouth texture.',
    price: 150,
    unit: 'per 500g',
    image: '/images/sweets/gulab-jamun.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'rasgulla',
    name: 'Rasgulla',
    category: 'sweets',
    description: 'Soft, spongy cottage cheese balls simmered in light sugar syrup flavored with rose water. A refreshing Bengali sweet that melts on the tongue.',
    price: 140,
    unit: 'per 500g',
    image: '/images/sweets/rasgulla.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'kaju-barfi',
    name: 'Kaju Barfi',
    category: 'sweets',
    description: 'Premium diamond-shaped cashew fudge topped with edible silver leaf (vark). Rich, smooth, and luxurious — made with the finest cashews and pure ghee.',
    price: 280,
    unit: 'per 500g',
    image: '/images/sweets/barfi.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'besan-ladoo',
    name: 'Besan Ladoo',
    category: 'sweets',
    description: 'Round golden balls of roasted chickpea flour, ghee, and powdered sugar, studded with almonds and raisins. A festive favorite with an irresistible aroma.',
    price: 160,
    unit: 'per 500g',
    image: '/images/sweets/ladoo.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'jalebi',
    name: 'Jalebi',
    category: 'sweets',
    description: 'Bright orange, crispy spiral-shaped deep-fried batter soaked in saffron sugar syrup. Best enjoyed hot and fresh — a beloved Indian street food dessert.',
    price: 100,
    unit: 'per 500g',
    image: '/images/sweets/jalebi.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'peda',
    name: 'Mathura Peda',
    category: 'sweets',
    description: 'Traditional milk fudge discs made by slow-cooking khoya with sugar and cardamom. Topped with pistachios and saffron strands. A divine temple-city delicacy.',
    price: 200,
    unit: 'per 500g',
    image: '/images/sweets/peda.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'motichoor-ladoo',
    name: 'Motichoor Ladoo',
    category: 'sweets',
    description: 'Vibrant orange ladoos made from tiny boondi drops, shaped into perfect spheres. Garnished with silver leaf and pistachios. A celebratory sweet for every occasion.',
    price: 180,
    unit: 'per 500g',
    image: '/images/sweets/motichoor-ladoo.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'samosa',
    name: 'Samosa',
    category: 'snacks',
    description: 'Golden, crispy triangular pastries filled with spiced potatoes, peas, and cumin. Served with tangy tamarind and zesty green mint chutney side dips.',
    price: 50,
    unit: 'per 2 pieces',
    image: '/images/sweets/samosa.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'namak-pare',
    name: 'Namak Pare',
    category: 'snacks',
    description: 'Crispy, diamond-shaped savory crackers made with refined flour, ajwain, and a hint of salt. Deep-fried to perfection — a crunchy snack for everyday munching.',
    price: 70,
    unit: 'per 250g',
    image: '/images/sweets/namak-pare.png',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'mathri',
    name: 'Mathri',
    category: 'snacks',
    description: 'Flaky, layered, crispy Rajasthani crackers spiced with ajwain and black pepper. Deep-fried for the perfect crunch — a timeless accompaniment to tea and pickles.',
    price: 90,
    unit: 'per 250g',
    image: '/images/sweets/mathri.png',
    isVeg: true,
    isAvailable: true,
  },
];

export const SWEET_CATEGORIES = [
  { id: 'all', name: 'All Items' },
  { id: 'sweets', name: 'Sweets' },
  { id: 'snacks', name: 'Snacks' },
];
